### ISSUE TITLE
Mobile and desktop clients

### ISSUE THREAD

**Issue by Ciao121** [Novage/p2p-media-loader#101]
Hi,
I'm trying to play a video from two client. One is Chrome on desktop ant the other is Chrome on mobile (android). Each client get the video via http and cannot see each other to use P2P.
I have the same problem on the demo site. Is it related to STUN (and isn't STUN used on the demo site)?
Thank you!

**Comment by mrlika** [comment]
Hi,

Most likely it is not because of STUN - it just tells to peers their external IP and port that helps them to connect. STUN requests are part of ICE that browsers use to establish P2P connections https://en.wikipedia.org/wiki/Interactive_Connectivity_Establishment

But it is not guaranteed that all the peers can connect - it may not be possible because of network configuration (i.e. NAT etc.)
