### ISSUE TITLE
can use this in flutter?

### ISSUE THREAD

**Issue by bookyo** [Novage/p2p-media-loader#131]
https://github.com/cloudwebrtc/flutter-webrtc   flutter have this WebRTC plugin, maybe can use p2p media loader in flutter.

**Comment by mrlika** [comment]
Flutter has WebRTC Data Channels support using this module. It means that it is possible to download data over P2P.

But unfortunately I can't find a way to play downloaded data easily. I can't find the support of Hls.js or Shaka Player engines (because of missing Media Source Extensions API implementation) or similar.

**Comment by bookyo** [comment]
Ok， thank you very much.
