### ISSUE TITLE
CMAF support

### ISSUE THREAD

**Issue by Anil-matcha** [Novage/p2p-media-loader#133]
Many players across the world are pushing for using CMAF to reduce latency for live streaming. 

Is there any plan to support CMAF in the future ? That would be a great addition.

**Comment by mrlika** [comment]
I think it is already there because Shaka Player engine partly supports CMAFF:

- https://github.com/google/shaka-player#hls-features
- https://github.com/google/shaka-player#media-container-and-subtitle-support
- https://github.com/google/shaka-player/blob/master/roadmap.md

It will be great if you can test CMAF in Shaka Player with and without P2P engine, and give your feedback.

I can't find CMAF support among Hls.js features unfortunately.

**Comment by amtbnagios** [comment]
https://github.com/google/shaka-player/pull/2473
Recognize new CMAF file extensions cmfv, cmfa, cmft in HLS
ISO-BMFF / MP4 / CMAF support

https://ll-hls-test.apple.com/cmaf/master.m3u8

http://novage.com.ua/p2p-media-loader/demo.html?url=https%3A%2F%2Fll-hls-test.apple.com%2Fcmaf%2Fmaster.m3u8&type=clappr

novage demo page can play it, is this p2p support?

**Comment by mrlika** [comment]
Hmm. I think no. The demo uses rather old Shaka Player. I will try to check with latest one soon.

**Comment by amtbnagios** [comment]
HI mrlika!

I create a cmaf stream for test (with Wowza Streaming Engine 4.8), the stream maybe :
hls cmaf url:
https://tw3.amtb.de/liveorigin/_definst_/cmaf/playlist_sfm4s.m3u8
dash cmaf url:
https://tw3.amtb.de/liveorigin/_definst_/cmaf/manifest.mpd

novage demo page can play them, I think it support p2p,  can you check it?

http://novage.com.ua/p2p-media-loader/demo.html?url=https%3A%2F%2Ftw3.amtb.de%2Fliveorigin%2F_definst_%2Fcmaf%2Fplaylist_sfm4s.m3u8&type=clappr

http://novage.com.ua/p2p-media-loader/demo.html?url=https%3A%2F%2Ftw3.amtb.de%2Fliveorigin%2F_definst_%2Fcmaf%2Fmanifest.mpd&type=clappr-shaka

BZW: This stream may be delayed by 20+ seconds, because this wowza will restart at 00:00 (+8:00tz)

Thanks very much!
