### ISSUE TITLE
[Question] What is best config ratio for httpDownloadProbability?

### ISSUE THREAD

**Issue by takid1412** [Novage/p2p-media-loader#19]
I just wonder why default config look like this:
```
httpDownloadProbability: 0.06,    
httpDownloadProbabilityInterval: 500,
```
As i understand, when `processSegmentsQueue` trigger, its used  `httpDownloadProbability` to random downloading through http. So with 0.06 ratio, after 20 times ~ 10 secs, all segment queued will download through http? Is it too short?
If i set `httpDownloadProbability: 0`, does p2p rate would be down?
Thanks.

**Comment by mrlika** [comment]
1) Each 500ms each peer gets 6% chance to download a segment over HTTP that is NOT DOWNLADING and NOT DOWNLOADED by other known peers.

2) If a peer starts download a segment over HTTP it inform other peers that the segment is DOWNLOADING.

3) Other peers will not try to download the segment over HTTP because of 1)

**Comment by takid1412** [comment]
So many thanks.
