### ISSUE TITLE
Shaka buffering frequently after using the loader

### ISSUE THREAD

**Issue by nodegin** [Novage/p2p-media-loader#43]
Hello, I don't know how to explain this issue very well.
I using this loader on VOD with 720/1080 videos, where segments usually ~10MB for 720 and ~20MB for 1080.
Without the loader, segments can be downloaded very fast via CDN
I am wondering if my current configuration is not suitable for VOD?

Also, I noticed the P2P request sequence seem to not ordered.
For example, say current segment is 100, next segment will be 101, but we got 102 instead, so we need to wait for 101 to load.
Maybe this cause the playback stucks frequently?

My current configuration:
```js
{
        loader: {
          cachedSegmentsCount: 75,
          cachedSegmentExpiration: 1000 * 60 * 15,
          simultaneousP2PDownloads: 4,
          httpDownloadProbability: 0.05,
          httpDownloadProbabilityInterval: 1000,
          bufferedSegmentsCount,
          trackerAnnounce: ['wss://tracker.openwebtorrent.com', 'wss://tracker.fastcast.nz'],
        },
        segments: {
          forwardSegmentCount: bufferedSegmentsCount,
          maxHistorySegments: 0,
        },
}
```

**Comment by Vladislavik** [comment]
Try set requiredSegmentsPriority to 5, it should download next 5 segments one by one, if they doesnot downloaded.
Also you can use httpDownloadProbability to 1

**Comment by nodegin** [comment]
@Vladislavik I just updated and it looks better than before, any other settings should I set to improve the load time for VOD?

**Comment by mrlika** [comment]
maxHistorySegments - should not be equal to 0. Shaka integration will not be able to get segment details by URL in this case.

P2P requests are not ordered. They are random.

Setting httpDownloadProbability to 1 will increase HTTP download ratio.

What is bufferedSegmentsCount value?

**Comment by nodegin** [comment]
@mrlika  I set `maxHistorySegments` to the same value as `cachedSegmentsCount` now, bufferedSegmentsCount was `25`

**Comment by mrlika** [comment]
If you still have problems with buffering - give the stream URL so we can investigate.

**Comment by Chocobozzz** [comment]
With `httpDownloadProbabilityInterval` to `500`, and `httpDownloadProbability` to `0.06`, we expect that the segments that cannot be downloaded with P2P will be download with HTTP after an average of 10 seconds right?

Because in my tests with the default settings, the player is blocked after the `requiredSegmentsPriority` segments were downloaded when there are no peers. It seems the `processSegmentQueue` (https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-core/lib/hybrid-loader.ts#L159) is not called again, and therefore segments cannot take their chance to be download with HTTP here: https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-core/lib/hybrid-loader.ts#L231

**Comment by mrlika** [comment]
What integration are you using - hls.js or Shaka Player? Also is it VOD or live stream?

**Comment by Chocobozzz** [comment]
hls.js with a VOD stream

**Comment by mrlika** [comment]
I can't reproduce when test with default parameters and https://wowza.peer5.com/vod/smil:bbb_abr.smil/playlist.m3u8 . Most likely I need to test your stream.

But the logic is slightly different.

Parameters httpDownloadProbabilityInterval and httpDownloadProbability are mostly responsible for segments to appear in the swarm - at least one peer should download a segment over HTTP ahead of playhead position (i.e with priority > requiredSegmentsPriority) to share over P2P with others.

So the parameters above are applied to the segments with priority > requiredSegmentsPriority.

Segments with priority <= requiredSegmentsPriority in most cases will be forced to be downloaded over HTTP (if HTTP source is responding correctly).

Playhead moves. While it moves processSegmentQueue should be called from time to time and when processSegmentQueue is called it should force HTTP download for not downloaded segments that are close to the playhead position (i.e. priority <= requiredSegmentsPriority)

**Comment by Chocobozzz** [comment]
Okay thanks @mrlika for the explanations.

My bad, I use https://github.com/streamroot/videojs-hlsjs-plugin with videojs so I should use [initHlsJsPlayer](https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-hlsjs/lib/index.ts#L20) instead of [initVideoJsContribHlsJsPlayer](https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-hlsjs/lib/index.ts#L40) (`hlsFragChanged` was not fired)

**Comment by nodegin** [comment]
Closing this issue as the problem seems suppressed
