### ISSUE TITLE
Expose infohash builder in options

### ISSUE THREAD

**Issue by Chocobozzz** [Novage/p2p-media-loader#44]
Hello,

It's difficult to use the library with private trackers, because the infohash is built with a prefix, a swarmId and a suffix. And the way the library builds it could change at any time (for example by using sha256 https://github.com/Novage/p2p-media-loader/blob/master/p2p-media-loader-core/lib/p2p-media-manager.ts#L97).

Is it possible to expose the infohash builder in options with some arguments (protocole version, playlist url etc)? 

Thanks

**Comment by mrlika** [comment]
p2p-media-loader-core is not aware of such details as manifest URL because it is intended to be applicable for any segmented stream (HLS, DASH etc.) each with its particularities. That is why core only knows about swarm ID that just should be passed to it and is generated by integration (i.e. hls.js or Shaka) and by default contains stream URL without query parameters and quality offset (i.e. https://akamai-axtest.akamaized.net/routes/lapd-v1-acceptance/www_c4/Manifest.m3u8+V0 for the first video quality) and if swarm ID is set in configuration parameters of hls.js or Shaka integration it will contain this swarm ID and quality offset (i.e. some_swarm+V0)

Then in the core to generate infohash we just add PEER_PROTOCOL_VERSION to the string. This simple trick allows to easily upgrade peers communication logic even on live sites - peers that use an old version of the protocol will not connect to a new come peers with a new version of the protocol but everything will keep working.

So there is no single endpoint in the project where all the raw data to generate infohash is directly met: stream URL, quality index/offset, peer protocol version.

We can add an async callback to configuration that will be responsible to generate infohash - 160bit value - from swarmId (string with master manifest URL or swarmId from configuration appended with current quality) and peer protocol version.

Or we can expose infohash changes in the events and somehow expose peer protocol version. Then to predict infohash by the URL and quality you can use simple code: 

```JS
const infohashString = `${peerProtocolVersion}${swarmIdorMasterManifestUrl}+V${qualityIndex}`;
// using Web Crypto API
const infohash1 = await crypto.subtle.digest("SHA-1", new TextEncoder().encode(infohasString));
// or the same using sha.js
const infohash2 = new sha1().update(infohashString).digest();
```
And I don't think that this algorithm will be a subject for frequent changes.

**Comment by Chocobozzz** [comment]
Thank you @mrlika, I'll generate these info hashes on the backend.
