### ISSUE TITLE
See video without CDN?

### ISSUE THREAD

**Issue by jimmywarting** [Novage/p2p-media-loader#60]
Is it possible to watch a HLS video without ever using the CDN?
can the manifest/fragments/pieces/quality be downloaded from other peers?

From the looks of it, it seems like it has to download the manifest file first, then after that it joins the swarm

**Comment by mrlika** [comment]
Live:
P2P Media Loader doesn't support this. And most likely the same issue is with other solutions. It is very hard to do live video streaming without a server.

Check this:
https://stackoverflow.com/questions/18318983/webrtc-scalable-live-stream-broadcasting-multicasting

VOD:
You can use WebTorrent without HTTP source (MP4 files).

But anyway without a server broadcast will not be very reliable.

**Comment by jimmywarting** [comment]
I know about webtorrent, but the video files is either dash or hls (not some torrent) and i can't change that, stuck with using hls...

**Comment by Yokutto** [comment]
Hi @jimmywarting,
It could be possible to streaming 100% of HLS video trough WebRTC, but your origin server will always upload to some users and the users will upload to each other. I do not recommend this method because the user experience will be poor if the browser wait to receive data from other user, so it always better to upload initial video data to all users trough CDN and them connect to WebRTC, you can save 80% of bandwidth and have good user experience. If you would like to stream a video 100% from torrent (using magnet link, etc...), it is possible only with source files like .mp4.

Also, if you have low user density, I do not recommend the use of P2P video streaming, because not all users is realible to upload data. I used streamroot with 5000+ concurrent users and saved only 60% of data because it have much videos. P2P video streaming is good in videos that have 100+ concurrent users, so you will save 95% of bandwidth on it

**Comment by Serkan-devel** [comment]
The STUN-Server might be a central point of failier in WebRTC already

**Comment by jimmywarting** [comment]
No it isn't, beside you can always use your own STUN/Trackers

**Comment by jimmywarting** [comment]
I might tackle this in another way by creating a mini TOR network with other people around the world...

**Comment by Yokutto** [comment]
I do not understand what you trying to say. Why you need to use HLS and DASH when you can stream using standard .MP4 in torrent network?

The solution on this repository only save video data using WebRTC, and please, do not use it to stream copyright protected content

**Comment by mrlika** [comment]
Check IPFS project. This beast aims to be fully decentralized:
[hlsjs-ipfs-loader](https://github.com/moshisushi/hlsjs-ipfs-loader)
[ipfs-live-streaming](https://github.com/tomeshnet/ipfs-live-streaming)
Most likely it will require coding with [libp2p](https://github.com/libp2p) and personal IPFS node setup.
