### ISSUE TITLE
httpUseRanges doesn't work when requiredSegmentsPriority: 0

### ISSUE THREAD

**Issue by thenikin** [Novage/p2p-media-loader#68]
Hi, thanks again for this new feature. Testing it with requiredSegmentsPriority: 0 it doesn't appear to be working as i don't see 206 partial content anymore. Any idea how to fix this?

thanks

**Comment by mrlika** [comment]
This feature works on slow peers when a segment becomes required (i.e. close to moving playhead) but it is still downloading over P2P. Then to have stable playback we cancel P2P download and continue HTTP download.

With `requiredSegmentsPriority` 0 segments never become required.

It is not recommended to have `requiredSegmentsPriority` set to 0 because required segments is playback buffer. Without buffer playback is not stable.
