### ISSUE TITLE
The system doesn't show anyone else but me

### ISSUE THREAD

**Issue by hungnm1518** [Novage/p2p-media-loader#8]
Thank you for this wonderful package. But I'm having a problem. The system works perfect between two computers on the same network. I get all the video uploaded to the other computer but doesn't work for people outside the network. P2P graph always only shows me. How to fix this issue?

**Comment by mrlika** [comment]
Yes, it is possible that peers can't connect mostly when both are behind NAT, that is not properly configured for P2P. Browsers use [ICE](https://en.wikipedia.org/wiki/Interactive_Connectivity_Establishment) to solve the issue but it may not help.

The issue is not related to P2P Media Loader directly but is related to WebRTC and ICE implementation and limitations in the browser.

If you can not find other peers to connect you will download directly from the source (i.e. fallback to CDN).
